apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-new
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/vikastecharavali/k8s_argocd
      targetRevision: main
      path: https://github.com/vikastecharavali/k8s_argocd/tree/main/k8s-new-app
  destination:
    namespace: default
    server: https://172.31.2.200:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true      
