apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-app
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
    ports:
      - port: 80
        protocol: TCP
        targetPort: 80

